mimir:
  gateway:
    ingress:
      hosts:
        - host: metrics-monitoring.kubrix.cape.rocks
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: mimir-nginx-tls
          hosts:
            - metrics-monitoring.kubrix.cape.rocks
